### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by therealbluepandabear** [Favade/ComposeCalculator#1]
dm me on discord thebluepandabear#9011

**Comment by Favade** [comment]
hey bro, thanks for reaching out again. I think I'm still blocked. Sorry about what happened before I genuinely didn't know I was getting a lot of bot comments about crypto and totally forget I messaged you hours prior. From this I want to better my skills and be the best android developer I can be. 
Thanks again man my discord is Zer0#5912

**Comment by therealbluepandabear** [comment]
ill dm u tomorrow and help u out
